### ISSUE TITLE
How to install inventory app on SNAP install of Nexcloud 27.1.6

### ISSUE THREAD

**Issue by Siukalo** [raimund-schluessler/inventory#498]
Hi

For the life of me I cannot work out how to install this on the snap version of nextcloud. The app is not visible in the nextcloud snap install version of the app store. Can someone please help me.

Thanks

Alan

**Comment by raimund-schluessler** [comment]
The app is in the [Nextcloud appstore](https://apps.nextcloud.com/apps/inventory) and should show up in the list of available apps in your Nextcloud instance. If it does not, please ask for help in the [forum](https://help.nextcloud.com/).
You can also download the [app package](https://github.com/raimund-schluessler/inventory/releases/download/v0.1.2/inventory.tar.gz) and unpack it into your apps folder.
