### ISSUE TITLE
[bug] feature-policy blocking QR code scanner

### ISSUE THREAD

**Issue by User65k** [raimund-schluessler/inventory#534]
Hi,

I am unable to use the QR Code scanner, as a Feature-Policy header forbidds it.
I could not find the header in my apache settings and apparently it's nextcloud that sets the header:
https://github.com/nextcloud/server/issues/22792 

Am I required to change the header via config.php or something? Or can the Inventory App adjust the headers value?

Versions:
Nextcloud Hub 7 (28.0.4)
Inventory 0.1.2

**Comment by umlaeute** [comment]
and/or do not offer the QR option if the feature policy does not allow it.

**Comment by raimund-schluessler** [comment]
The app sets the CSP here:

https://github.com/raimund-schluessler/inventory/blob/8ad234967611f49d09cbb856992279e43a45c77e/lib/Controller/PageController.php#L68-L72

Not sure, why this does not work for you.

**Comment by raimund-schluessler** [comment]
@User65k Could you please show the error message from the console that you get when trying to read a barcode?

**Comment by User65k** [comment]
It's not the CSP it's the Feature-Policy. Jet another header.
I will Post the error in the evening

**Comment by User65k** [comment]
In Chromium I get `[Violation] Permissions policy violation: camera is not allowed in this document.`

The header itself is `Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'self';microphone 'none';payment 'none'`

It works in Firefox, with the same header present

**Comment by raimund-schluessler** [comment]
We can probably set the feature policy similar to here:

https://github.com/nextcloud/server/blob/19602a0cee03afe954d3996b3cdcb7c3800e9b5d/apps/dashboard/lib/Controller/DashboardController.php#L101-L103

with `addAllowedCameraDomain`.

See also
https://github.com/nextcloud/server/blob/19602a0cee03afe954d3996b3cdcb7c3800e9b5d/lib/public/AppFramework/Http/EmptyFeaturePolicy.php#L76-L78

**Comment by raimund-schluessler** [comment]
> In Chromium I get `[Violation] Permissions policy violation: camera is not allowed in this document.`
> 
> The header itself is `Feature-Policy: autoplay 'self';camera 'none';fullscreen 'self';geolocation 'self';microphone 'none';payment 'none'`
> 
> It works in Firefox, with the same header present

Which Chromium version do you use? It works fine for me with Chromium 124.0 on Ubuntu, so I cannot reproduce or test a fix.

**Comment by raimund-schluessler** [comment]
PR is in #548. Could you check whether that fixes it for you?
