### ISSUE TITLE
[bug] treat whitespace in GTIN as empty

### ISSUE THREAD

**Issue by umlaeute** [raimund-schluessler/inventory#537]
steps to reproduce:
- create a new item (via the CSV importer)
- navigate to the item
- select the `Edit item` menu from the pulldown
  - notice that you can now edit all the fields
- edit the item (change the description, add some tags, add a comment)
- Click on the :heavy_check_mark: (that says `Save changes` via a tooltip)
- note that all your changes are gone :disappointed: 
- select the `Edit item` menu from the pulldown again
- note that all your changes are back
- reload the page
- select the `Edit item` menu from the pulldown again
- note that all your changes are gone for good :sob:

**Comment by umlaeute** [comment]
obviously a duplicate of #536 .

however, note that i *do* click on the :heavy_check_mark: to save the item

**Comment by raimund-schluessler** [comment]
> obviously a duplicate of #536 .
> 
> however, note that i _do_ click on the ✔️ to save the item

That is weird. It works here. Do you see a request to the server, when you click the button?

**Comment by umlaeute** [comment]
there's a `PATCH` request, but it seems it is filed under *400 Bad Request":
```
1.2.3.4 - - [02/May/2024:10:04:52 +0200] "PATCH /index.php/apps/inventory/api/v1/item/1/edit HTTP/1.1" 400 1223 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:109.0) Gecko/20100101 Firefox/115.0"
```

**Comment by umlaeute** [comment]
ah, the server responds with:
```json
{
  "status":400,
  "message":"The provided GTIN is invalid."
}
```

indeed, my GTIN is empty (which i think should be allowed; not every item has a GTIM)

**Comment by raimund-schluessler** [comment]
> ah, the server responds with:
> 
> ```json
> {
>   "status":400,
>   "message":"The provided GTIN is invalid."
> }
> ```
> 
> indeed, my GTIN is empty (which i think should be allowed; not every item has a GTIM)

Are you sure it's empty and not whitespace? I can save empty GTINs but adding a whitespace makes it fail (which should probably be handled more gracefully).

**Comment by umlaeute** [comment]
> Are you sure it's empty and not whitespace? I can save empty GTINs but adding a whitespace makes it fail.

i'm not sure.

I changed it back to an empty GTIN (so it now shows a placeholder `GTIN`), and i can indeed save as expected.
I guess, when adding the item, I used ` ` (a single whitespace) in the CSV.
