### ISSUE TITLE
Cant add items

### ISSUE THREAD

**Issue by BIRDHEart** [raimund-schluessler/inventory#574]
> no matter what we try, can't add items, can you please provide an example?

**Comment by mahoneyr** [comment]
I've had some luck typing an item name in the box followed by several semicolons and then the add button becomes enabled. I haven't found a practical workflow yet.

**Comment by wonka929** [comment]
Some item are failing in the mass insert process.
Example:

{"item":{"id":173,"name":"RMS621-41AAA1441","maker":"Endress e Hauser","description":"Display Remoto per RSM 621 SN F200850422E","item_number":"","link":"","gtin":"RMS621-41AAA1441","details":"","comment":"","type":"Product","instances":[{"place":"","price":"","count":"1","available":"1","vendor":"","date":"","comment":""}],"syncStatus":{"type":"unsynced","message":"The item has not been saved to the server yet."},"tags":[],"path":""}}

There is no feedback on the reason for failure, I'm not able to fix all these items.
Any int on requirements for text?

**Comment by raimund-schluessler** [comment]
> "gtin":"RMS621-41AAA1441"

This is not a valid GTIN. Either provide a valid one or an empty string.

**Comment by wonka929** [comment]
Oky, so i need to ask: which is the validation criteria?
Maybe i just need to modify some of them, but I can't understand a priori which one passes the test and which one doesn't.

**Comment by raimund-schluessler** [comment]
> Oky, so i need to ask: which is the validation criteria?

Here you can find information about GTIN: https://en.wikipedia.org/wiki/Global_Trade_Item_Number

Inventory specifically expects GTIN-13 which is equivalent to the EAN-13 (barcode).

Here you can find how to calculate whether a GTIN is valid: https://www.gs1.org/services/how-calculate-check-digit-manually
But I don't see a reason why one would want that, as most (commercial) items should have a GTIN provided by the vendor.

If you want to use your own item number / ID code, just use the `item_number` field (4th position in the CSV string).

**Comment by raimund-schluessler** [comment]
> no matter what we try, can't add items, can you please provide an example?

To answer the original question: Inventory currently only offers a "mass import" via CSV strings. They have to follow this scheme (as printed above the input field):
`<name>; <maker>; <description>; <item_number>; <link>; <GTIN>; <details>; <comment>; <type>; <place>; <price>; <count>; <available>; <vendor>; <date>; <tags>; <related>; `

`name` must not be empty, `name` and `maker` must not exceed 100 chars, `link` not exceed 255 and `comment`, `details` & `description` not exceed 65000 and the `GTIN` must be valid. `count` and `available` must be numbers.

Sorry that this is so involved, there will be an option to add single items at some point (see #481) and somehow reporting what failed would be good as well.
